package hooks

import "fmt"

// GenerateHookScript generates the hook notification script content
func GenerateHookScript(port int) string {
	return fmt.Sprintf(`#!/bin/bash
# Claude Watch Status - Hook Notification Script
# Generated by: claude-watch-status init
# DO NOT EDIT - This file is managed by claude-watch-status

set -e

CWS_HOST="${CWS_HOST:-127.0.0.1}"
CWS_PORT="${CWS_PORT:-%d}"
CWS_TIMEOUT="${CWS_TIMEOUT:-2}"

# Read hook data from stdin
HOOK_DATA=$(cat)

# Send to daemon (fail silently to not block Claude Code)
curl -X POST "http://${CWS_HOST}:${CWS_PORT}/api/hooks" \
  -H "Content-Type: application/json" \
  -d "$HOOK_DATA" \
  --max-time "$CWS_TIMEOUT" \
  --connect-timeout 1 \
  --silent \
  --show-error 2>/dev/null || true

exit 0
`, port)
}
